import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[5, 6], [7, 8], [9, 10]])
print(A)
print(B)
print("Addition:", A + B)
print("Subtraction:", A - B)
print("Element-wise Multiplication:", A * B)
print("Element-wise Division:", A / B)
print("Matrix Multiplication:", A @ B.T)
print("Transpose of A:", A.T)
print("Inverse of A:", np.linalg.inv(A.T @ A))
print("Determinant of A:", np.linalg.det(A.T @ A))
print("Eigenvalues of A:", np.linalg.eigvals(A.T @ A))
print("inverse of A:", np.linalg.inv(A.T @ A))