import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)
arr = np.zeros((3, 3))
print(arr)
arr = np.ones((2, 2))
print(arr)
arr = np.full((3, 3), 7)
print(arr)
arr = np.arange(0, 10, 2)
print(arr)
arr = np.linspace(0, 1, 5)
print(arr)
arr = np.concatenate((np.array([1, 2, 3]), np.array([4, 5, 6])))
print(arr)
arr = np.stack((np.array([1, 2, 3]), np.array([4, 5, 6])), axis=0)
print(arr)
arr = np.hstack((np.array([1, 2, 3]), np.array([4, 5, 6])))
print(arr)
arr = np.vstack((np.array([1, 2, 3]), np.array([4, 5, 6])))
print(arr)  
arr = np.split(np.array([1, 2, 3, 4, 5, 6]), 3)
print(arr)  
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1:4])
print(arr[-1])  
arr = np.append(arr, 6)
print(arr)  
arr = np.insert(arr, 0, 0)
print(arr)  
arr = np.delete(arr, 0)
print(arr)  