import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt 
df=pd.read_csv('data.csv')
df.columns
df.skew(numeric_only=True)
df.kurt(numeric_only=True)        
sns.histplot(df['salary currency'])
plt.show()
sns.histplot(df['salary in USD'])
plt.show()
sns.histplot(df['experience'])  
plt.show()
sns.histplot(df['education'])
plt.show()
sns.histplot(df['city'])
plt.show()  
sns.histplot(df['company size'])
plt.show() 
sns.histplot(df['employ residence'])
plt.show()
sns.histplot(df['job title'])
plt.show()
sns.histplot(df['work year'])
plt.show()
sns.histplot(df['remote ratio'])    
plt.show()
sns.histplot(df["company location"])
plt.show()
sns.histplot(df['salary'])
plt.show()
